"""02_initial-db

Revision ID: 03263da297a6
Revises: e6e92618013b
Create Date: 2024-02-07 12:36:07.625736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03263da297a6'
down_revision: Union[str, None] = 'e6e92618013b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column(
        'description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'description')
    # ### end Alembic commands ###
